# Generated by Django 5.2.1 on 2025-06-16 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha', models.CharField(max_length=40)),
                ('message', models.TextField()),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.CharField(max_length=255)),
                ('author_date', models.DateTimeField()),
                ('author_login', models.CharField(blank=True, max_length=255, null=True)),
                ('html_url', models.URLField()),
                ('additions', models.IntegerField(blank=True, null=True)),
                ('deletions', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='repositories.repository')),
            ],
            options={
                'verbose_name': 'Commit',
                'verbose_name_plural': 'Commits',
                'unique_together': {('repository', 'sha')},
            },
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pr_id', models.BigIntegerField()),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('state', models.CharField(max_length=20)),
                ('draft', models.BooleanField(default=False)),
                ('merged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('html_url', models.URLField()),
                ('user_login', models.CharField(max_length=255)),
                ('head_ref', models.CharField(max_length=255)),
                ('head_sha', models.CharField(max_length=40)),
                ('base_ref', models.CharField(max_length=255)),
                ('base_sha', models.CharField(max_length=40)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='repositories.repository')),
            ],
            options={
                'verbose_name': 'Pull Request',
                'verbose_name_plural': 'Pull Requests',
                'unique_together': {('repository', 'pr_id')},
            },
        ),
    ]
