# Generated by Django 5.0.14 on 2025-06-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_repository_last_synced_at_commit_pullrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='cycle_time',
            field=models.IntegerField(blank=True, help_text='Cycle time (PR open to merge)', null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='first_commit_to_open',
            field=models.IntegerField(blank=True, help_text='Time from first commit to PR creation', null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='first_response_time',
            field=models.IntegerField(blank=True, help_text='Time from PR creation to first review/comment', null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='first_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='last_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='lead_time_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='merge_time',
            field=models.IntegerField(blank=True, help_text='Time from final approval to merge', null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='merge_to_deploy',
            field=models.IntegerField(blank=True, help_text='Time from merge to deployment', null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='rework_cycles',
            field=models.IntegerField(default=0, help_text='Number of rework cycles'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='rework_time',
            field=models.IntegerField(blank=True, help_text='Time spent in rework cycles', null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='total_lead_time',
            field=models.IntegerField(blank=True, help_text='Total lead time in seconds', null=True),
        ),
    ]
