# Generated by Django 5.0.14 on 2025-06-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_repository_last_synced_at_commit_pullrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='merge_commit_sha',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='requested_reviewers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='reviewers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['repository', 'state'], name='repositorie_reposit_8e2059_idx'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['merged_at'], name='repositorie_merged__7c576e_idx'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['created_at'], name='repositorie_created_212231_idx'),
        ),
    ]
